name: hub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  location: ^2.3.5
  font_awesome_flutter: ^8.5.0
  firebase_auth: ^0.15.3+1
  google_sign_in: ^4.1.1
  geolocation: ^1.1.2
  google_maps_flutter: ^0.5.22+2
  flutter_map:
  json_annotation:
  json_serializable:
  build_runner:
  http: any
  sqflite: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
       - images/guia_gay_.png
       - images/guia_gay_logo.png
       - images/ic_roteiro_clubs_1.png
       - images/ic_roteiro_bares.png
       - images/ic_roteiro_cafe.png
       - images/ic_roteiro_cidadania.png
       - images/cine_cabines.png
       - images/ic_roteiro_compras_3.png
       - images/esportes.png
       - images/ic_roteiro_igrejas.png
       - images/ic_roteiro_apoio_turistico.png
       - images/saunas.png
       - images/google_logo.png
       - images/guia_bh.jpg
       - images/guia_df.jpg
       - images/guia_floripa.jpg
       - images/guia_salvador.jpg
       - images/guia.png
